require("joao-nvim-config.plugins-setup")
require("joao-nvim-config.core.options")
require("joao-nvim-config.core.keymaps")
require("joao-nvim-config.core.colorscheme")
require("joao-nvim-config.plugins.nvim-tree")
require("joao-nvim-config.plugins.lualine")
